constant_contact.account.*:
  type: config_entity
  label: 'Constant Contact account settings'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    api_key:
      type: string
      label: 'API key'
    application:
      type: string
      label: 'Application name'
    secret:
      type: string
      label: 'Secret'
    access_token:
      type: string
      label: 'Access token'

constant_contact.settings:
  type: config_object
  label: 'Constant Contact settings'
  mapping:
    cc_address_provider:
      type: string
      label: 'The module that manages contact addresses'
    cc_profile_type:
      type: string
      label: 'The profile type for contact details'
    cc_source:
      type: string
      label: 'How a contact was added'
    cc_source_details:
      type: string
      label: 'The application used to add the contact'
    cc_signup_title:
      type: string
      label: 'Title on subscription form'
    cc_signup_description:
      type: string
      label: 'Description on subscription form'
    cc_signup_registration:
      type: booelan
      label: 'Users can subscribe to mailing lists at registration'
    cc_show_format_choice:
      type: boolean
      label: 'Display email format options to users'
    cc_format_default:
      type: string
      label: 'Default email format'
    cc_opt_in_default:
      type: boolean
      label: 'Opt-in users to mailing lists by default'
    cc_contact_list_sort_field:
      type: string
      label: 'Contact list field to sort by'
    cc_contact_list_sort_direction:
      type: string
      label: 'Direction of sorting the contact list'
    cc_cache_expire_default:
      type: integer
      label: 'How long to keep data in the cache'
    cc_sync_users:
      type: boolean
      label: 'Sync users with Constant Contact'
