constant_contact.account.*:
  type: config_entity
  label: 'Constant Contact account settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    application:
      type: string
      label: 'Application name'
    secret:
      type: string
      label: 'Secret'
    access_token:
      type: string
      label: 'Access token'

constant_contact.settings:
  type: config_object
  label: 'Constant Contact settings'
  mapping:
    address_provider:
      type: string
      label: 'Address provider'
